version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/lama-dal.war lama-dal.war
artifacts:
  files:
    - lama-dal.war
  base-directory: 'target/lama-dal.war'